### ISSUE TITLE
End to End Instruction

### ISSUE THREAD

**Issue by benignavesh** [eihli/image-table-ocr#1]
Hi, glad that I found this. Kudos to the developers first of all. I was just wondering if you can provide an end to end descriptive steps from input PDF to output CSV. It's not exactly clear from the shell script you gave. Thanks!

**Comment by sarthak405** [comment]
I agree. Just stumbled across this and it looks amazing, I was trying to convert a PDF to CSV using the shell script, and ran into this error.

```
: not foundge_table_ocr.sh: 2: ./scipt_image_table_ocr.sh:
: not foundge_table_ocr.sh: 4: ./scipt_image_table_ocr.sh:
/usr/bin/python: No module named table_ocr
cat: /tmp/pdf-images.txt: No such file or directory
cat: /tmp/extracted-tables.txt: No such file or directory
cat: /tmp/extracted-cells.txt: No such file or directory
: not foundge_table_ocr.sh: 9: ./scipt_image_table_ocr.sh:
./scipt_image_table_ocr.sh: 10: ./scipt_image_table_ocr.sh: Syntax error: word unexpected (expecting "do")
```

Could you please provide descriptive steps to run it?

**Comment by eihli** [comment]
Thanks for the kind words.

Did you see the example usage here?

 https://eihli.github.io/image-table-ocr/pdf_table_extraction_and_ocr.html#org3ae1ded

```
#!/bin/sh

PDF=$1

python -m table_ocr.pdf_to_images $PDF | grep .png > /tmp/pdf-images.txt
cat /tmp/pdf-images.txt | xargs -I{} python -m table_ocr.extract_tables {}  | grep table > /tmp/extracted-tables.txt
cat /tmp/extracted-tables.txt | xargs -I{} python -m table_ocr.extract_cells {} | grep cells > /tmp/extracted-cells.txt
cat /tmp/extracted-cells.txt | xargs -I{} python -m table_ocr.ocr_image {} --psm 7 -l table-ocr

for image in $(cat /tmp/extracted-tables.txt); do
    dir=$(dirname $image)
    python -m table_ocr.ocr_to_csv $(find $dir/cells -name "*.txt")
done
```

The package is still relatively new so a lot of details haven't been ironed out and documentation might not match the code. @sartak405, what is `scipt_image_table_ocr.sh`? I can't make sense of that error message and I think knowing what was inside that shell script would help.

edit: Ah, Sartak405, I think I see. `scipt_image_table_ocr.sh` probably has that code that I pasted above. That 3rd line in your message is the relevant one. The shell script relies on the `table_ocr` python package being installed. `table_ocr` isn't on PyPi yet, so you'll need to install it from this repo with `pip install https://github.com/eihli/image-table-ocr/tarball/master\#egg\=table_ocr`

**Comment by nickmitch89** [comment]
This package looks really useful. But do you have any advice for using the package in a python program?  I'm on windows 10, and am not really sure how to use the shell program.

**Comment by eihli** [comment]
@nickmitch89 Get the `table_ocr` directory on the path that python searches for modules. You'll have to look into how to do that, but it's probably doing a `pip install -e image-table-ocr/table_ocr`. Then you can import any of the modules in your python program. `from exract_tables import extract_cell_images_from_table`.

**Comment by eihli** [comment]
Added to readme and pushed package to PyPi.

```
pip3 install table_ocr
python3 -m table_ocr.demo https://raw.githubusercontent.com/eihli/image-table-ocr/master/resources/test_data/simple.png
```

**Comment by MapZombie** [comment]
I don't think this really explained how to use it within a Python program. An example of the bash script but in Python would be very useful.

I'm using a Windows machine and this bash script is not helping.
