### ISSUE TITLE
Error opening data file /usr/share/tessdata/table-ocr.traineddata

### ISSUE THREAD

**Issue by ultrabug** [eihli/image-table-ocr#3]
Hello, thanks for this repo!

It's a bit hard to understand how to get it working when you simply start with a PNG image and want to give it a try. So I'm trying with a sample file you're giving.

I run
```
python -m table_ocr.extract_tables resources/examples/example-page-table-000.png | grep table > /tmp/extracted-tables.txt
cat /tmp/extracted-tables.txt | xargs -I{} python -m table_ocr.extract_cells {} | grep cells > /tmp/extracted-cells.txt
cat /tmp/extracted-cells.txt | xargs -I{} python -m table_ocr.ocr_image {} --psm 7 -l table-ocr
```

and I get

```
pytesseract.pytesseract.TesseractError: (1, 'Error opening data file /usr/share/tessdata/table-ocr.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory. Failed loading language \'table-ocr\' Tesseract couldn\'t load any languages! Could not initialize tesseract.')
```

I don't understand is how to get the `table-ocr.traineddata` file that tesseract seems to be looking for?

Thanks again

**Comment by eihli** [comment]
Check out section 4.1 of https://eihli.github.io/image-table-ocr/pdf_table_extraction_and_ocr.html#orgc895682

```
Once the training is complete, there will be a new file tesstrain/data/<model-name>.traineddata. 
Copy that file to the directory Tesseract searches for models. 
On my machine, it was /usr/local/share/tessdata/. 
```

**Comment by ultrabug** [comment]
Thanks @eihli ; mind you share the rationale of what could prevent us from shipping those trained data?

I have the feeling that would help people use your code without having to find pdfs (or images) to train from. I mean, if you already did it, why not propose it as-is?

**Comment by eihli** [comment]
I was thinking the training would be so specific to the particular font and image quality that my personal trained data wouldn't be of much use. I'd rather make it clear in the documentation how to train data so that there is no lock-in to one particular trained model.

But you're right that I think I could at least include the base data from tesseract so that *something* works out-of-the-box.

**Comment by ultrabug** [comment]
Thanks @eihli

**Comment by eihli** [comment]
Just pushed a commit that includes the trained data.

Now you should just be able to `pip install dist/table_ocr-<version >= 0.2.0>-py3-none-any.whl` and it will work out of the box.

The traineddata is installed wherever pip installs the package. So you'll need to include that as the tessdata_dir.

`python -m table_ocr.ocr_image {} --psm 7 -l table-ocr --tessdata-dir ~/.local/lib/python3.8/site-packages/table_ocr/tessdata` for example. Or `python -m table_ocr.ocr_image <image_path>` and it will default to `--psm 7 -l table-ocr` and the correct tessdata-dir.
