### ISSUE TITLE
ModuleNotFoundError: No module named 'table_ocr' (windows/mac)

### ISSUE THREAD

**Issue by allensh11** [eihli/image-table-ocr#4]
Hi - thank you for creating this - it really looks useful!
When I try `pip3 install table_ocr` followed by `python3 -m table_ocr.demo https://raw.githubusercontent.com/eihli/image-table-ocr/master/resources/test_data/simple.png`

I always get the same problem - `No module named 'table_ocr'`

The installation runs successfully, all the dependencies are installed.

Happens both on Windows and Mac. Am I missing something?

![image](https://user-images.githubusercontent.com/53672307/102282243-2c3ffc80-3f95-11eb-849f-35cab3879dc6.png)

**Comment by eihli** [comment]
I forgot to add `__init__.py` to the `table_ocr/demo` package. I'll push a fix. Thanks for reporting this!

**Comment by eihli** [comment]
It should be working now. `pip3 uninstall table_ocr && pip3 install table_ocr && python3 -m table_ocr.demo https://raw.githubusercontent.com/eihli/image-table-ocr/master/resources/test_data/simple.png`
