### ISSUE TITLE
unable to run the code

### ISSUE THREAD

**Issue by AnkurAlankarBiswal** [eihli/image-table-ocr#9]
Can you please share the setup instructions getting below error 

"pytesseract.pytesseract.TesseractError: (1, 'Error opening data file C:\\Users\\Ankur.Biswal\\AppData\\Local\\Tesseract-OCR\\tessdata/tessdata/eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory. Failed loading language \'eng\' Tesseract couldn\'t load any languages! Could not initialize tesseract.')"

**Comment by eihli** [comment]
This looks like an error that is specific to your environment and related to Tesseract, not this image-table-ocr library. I can't really provide any more help than the error message. Does that `eng.traineddata` file exist? Is `TESSDATA_PREFIX` set to the parent directory? If you have confirmed both of those facts, it could be an issue with file permissions.
